---
title: "Variable importance calculated based on CP profiles"
author: "Anna Kozak"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Let $vip_j^{CP}(x)$ denotes variable importance calculated based on CP profiles in point x for variable $j$.
$$vip_{j}^{CP}(x)=\int_{-\infty}^{\infty}|CP^{f,j,x}(z)-f(x)|dz$$

The straightforward estimator for $vip_j^{CP}(x)$ is
$$\widehat{vip_j^{CP}(x)} = \frac{1}{n} \sum_{i=1}^{n}|CP^{f,j,x}(x_i)-f(x)|.$$



## Modification of this coefficient

### Absolute deviations calculted as a distance from average $\overline{CP}^{f,j,c}(z)$

$$vip_j^{CP}(x)=\frac{1}{n}\sum_{i=1}^{n}|CP^{f,j,x}(x_i)-\overline{CP}^{f,j,c}(z)|$$

### Root from average squares between CP profiles and average $f(x)$
$$vip_j^{CP}(x)=\sqrt{\frac{1}{n}\sum_{i=1}^{n}(CP^{f,j,x}(x_i)-f(x))^2}$$


### Root from average squares  between CP profiles and average $\overline{CP}^{f,j,c}(z)$
$$vip_j^{CP}(x)=\sqrt{\frac{1}{n}\sum_{i=1}^{n}(CP^{f,j,x}(x_i)-\overline{CP}^{f,j,c}(z))^2}$$

### Absolute deviations calculated as a distance from average $\overline{CP}^{f,j,c}(z)$ and weighted based on the density of variable x^j.

$$vip_j^{CP}(x) = \frac{1}{n} \sum_{i=1}^{n}|p_iCP^{f,j,x}(x_i)-\overline{CP}^{f,j,c}(z)|.$$

### Absolute deviations calculated as a distance from average $f(x)$ and weighted based on the density of variable x^j.

$$vip_j^{CP}(x) = \frac{1}{n} \sum_{i=1}^{n}|p_iCP^{f,j,x}(x_i)-f(x)|.$$


### Root from average squares  between CP profiles and average $\overline{CP}^{f,j,c}(z)$ and weighted based on the density of variable x^j.

$$vip_j^{CP}(x) =\sqrt{ \frac{1}{n} \sum_{i=1}^{n}(p_iCP^{f,j,x}(x_i)-\overline{CP}^{f,j,c}(z))^2}.$$



###  Root from average squares  between CP profiles and average $f(x)$ and weighted based on the density of variable x^j.

$$vip_j^{CP}(x) =\sqrt{ \frac{1}{n} \sum_{i=1}^{n}(p_iCP^{f,j,x}(x_i)-f(x))^2}.$$
