#' Calculated empirical density.
#'
#' This function calculate an empirical density based on variable split from Ceteris Paribus profiles.
#'
#' @param cp data.frame generated by ingredients::ceteris_paribus()
#' @param df data.frame with raw data to model
#' @param variable_split list generated by ingredients::calculate_variable_split()
#'
#' @return Return an empirical density based on ingredients::calculate_variable_split().
#'
#' @examples
#' \dontrun{
#'
#' split <- ingredients::calculate_variable_split(df, variables = colnames(df))
#' CalculateEmpiricalDensity(df, variable_split = split)
#' }
#'
#' @export
#'
CalculateEmpiricalDensity <- function(cp, df, variable_split){
  if (!(c("ceteris_paribus_explainer") %in% class(cp)))
    stop("The CalculateEmpiricalDensity() function requires an object created with ceteris_paribus() function.")
  if (!(c("list") %in% class(variable_split)))
      stop("The CalculateEmpiricalDensity() function requires an object created with calculate_variable_split() function.")
  if (!(c("data.frame") %in% class(df)))
      stop("The CalculateEmpiricalDensity() function requires a data.frame.")
  cut_range <- lapply(as.vector(unique(cp$`_vname_`)), function(x){
    data.frame(table(cut(df[, as.vector(as.character(x))],
                        unique(c(min(df[, as.vector(as.character(x))]),
                        variable_split[[as.character(x)]],
                        max(df[, as.vector(as.character(x))]))), include.lowest = TRUE))/nrow(df))
    })
  names(cut_range) <- as.vector(unique(cp$`_vname_`))
  cut_range
}

