#' Calculated empirical density and weight based on variable split.
#'
#' This function calculate an empirical density of raw data based on variable split from Ceteris Paribus profiles. Then calculated weight for values generated by ingredients::ceteris_paribus().
#'
#' @param profiles data.frame generated by ingredients::ceteris_paribus()
#' @param data data.frame with raw data to model
#' @param variable_split list generated by ingredients::calculate_variable_split()
#'
#' @return Return an weight based on empirical density.
#'
#' @examples
#' \dontrun{
#'
#' split <- ingredients::calculate_variable_split(data, variables = colnames(data))
#' calculate_weight(profiles, data, variable_split = split)
#' }
#'
#' @export
#'
calculate_weight <- function(profiles, data, variable_split){
  if (!(c("ceteris_paribus_explainer") %in% class(profiles)))
    stop("The CalculateWeight() function requires an object created with ceteris_paribus() function.")
  if (!(c("list") %in% class(variable_split)))
    stop("The CalculateWeight() function requires an object created with calculate_variable_split() function.")
  if (!(c("data.frame") %in% class(data)))
    stop("The CalculateWeight() function requires a data.frame.")
  cut_range <- lapply(unique(profiles$`_vname_`), function(x){
    data.frame(table(cut(data[, as.vector(as.character(x))],
                         unique(c(min(data[, as.vector(as.character(x))]),
                                  variable_split[[as.character(x)]],
                                  max(data[, as.vector(as.character(x))]))), include.lowest = TRUE))/nrow(data))})
  weight_range <- lapply(unique(profiles$`_vname_`), function(x){
    data.frame("Var1" = cut(profiles[profiles$`_vname_` == x, as.vector(as.character(x))],
                            unique(c(min(data[, as.vector(as.character(x))]),
                                     variable_split[[as.character(x)]],
                                     max(data[, as.vector(as.character(x))]))), include.lowest = TRUE),
               "Value" = profiles[profiles$`_vname_` == x, as.vector(as.character(x))])
  })
  names(cut_range) <- as.vector(unique(profiles$`_vname_`))
  names(weight_range) <- as.vector(unique(profiles$`_vname_`))
  weight <- lapply(as.vector(unique(profiles$`_vname_`)), function(x){
    unname(unlist(dplyr::left_join(weight_range[[x]], cut_range[[x]], by = "Var1")["Freq"]))
  })
  names(weight) <- as.vector(unique(profiles$`_vname_`))
  weight
}

