#' Global Variable Importance measure based on Partial Dependence profiles.
#'
#' This function calculate global importance measure.
#'
#' @param profiles \code{data.frame} generated by \code{ingredients::partial_dependence()}
#' @param grid_points maximum number of points for profile calculations, the default values is 101, the same as in \code{ingredients::ceteris_paribus}, if you use a different on, you should also change here
#' @return A \code{data.frame} of the class \code{global_variable_importance}.
#' It's a \code{data.frame} with calculated global variable importance measure.
#' @examples
#'
#'
#' library("DALEX")
#' data(apartments)
#'
#' library("randomForest")
#' apartments_rf_model <- randomForest(m2.price ~ construction.year + surface +
#'                                     floor + no.rooms, data = apartments)
#'
#' explainer_rf <- explain(apartments_rf_model, data = apartmentsTest[,2:5],
#'                         y = apartmentsTest$m2.price)
#'
#' library("ingredients")
#' profiles <- partial_dependence(explainer_rf)
#'
#' library("vivo")
#' global_variable_importance(profiles)
#'
#'
#' @export
#'


global_variable_importance <- function(profiles, grid_points = 101){
  if (!(c("aggregated_profiles_explainer", "partial_dependence_explainer") %in% class(profiles)))
    stop("The global_variable_importance() function requires an object created with partial_dependence() or aggregate_profiles() function.")


  avg_yhat <- lapply(unique(profiles$`_vname_`), function(x){
    mean(profiles$`_yhat_`[profiles$`_vname_` == x])
  })
  names(avg_yhat) <- unique(profiles$`_vname_`)

  result <- unlist(lapply(unique(profiles$`_vname_`), function(w){
    mean(abs((profiles[profiles$`_vname_` == w, "_yhat_"] - avg_yhat[[w]])))
    }))


  gvivo <- data.frame(variable_name = unique(profiles$`_vname_`), measure = result)
  class(gvivo) = c("global_importance", "data.frame")
  lvivo
}

