#' Local Variable Importance measure based on Ceteris Paribus profiles.
#'
#' This function calculate local importance measure in eight variants.
#'
#' @param cp data.frame generated by ingredients::ceteris_paribus()
#' @param df data.frame with raw data to model
#' @param absolute_deviation logical parameter, if `absolute_deviation = TRUE` then measue is calculated as absolute deviation, else is calculated as a root from average squares
#' @param point logical parameter, if `point = TRUE` then measure is calculated as a distance from f(x), else measure is calculated as a distance from average CP
#' @param density logical parameter, if `density = TRUE` then measure is weighted based on the density of variable, else is not weighted
#'
#' @return A list of the class 'local_variable_importance'.
#' It's a list with calculated local variable importance measure.
#' @examples
#' \dontrun{
#'
#' LocalVariableImportance(cp, df, absolute_deviation = TRUE, point = TRUE, density = FALSE)
#'
#' }
#'
#' @export
#'


LocalVariableImportance <- function(cp, df, absolute_deviation = TRUE, point = TRUE, density = TRUE){
  if (!(c("ceteris_paribus_explainer") %in% class(cp)))
    stop("The LocalVariableImportance() function requires an object created with ceteris_paribus() function.")
  if (!c("data.frame") %in% class(df))
    stop("The LocalVariableImportance() function requires a data.frame.")

  avg_yhat <- lapply(unique(cp$`_vname_`), function(x){
    mean(cp$`_yhat_`[cp$`_vname_` == x])
  })
  names(avg_yhat) <- unique(cp$`_vname_`)

  variable_split <- ingredients::calculate_variable_split(df, variables = colnames(df))

  weight <- LocalVariableImportanceViaOscillations::CalculateWeight(cp, df, variable_split = variable_split)

  obs <- attr(cp, "observations")


  if(absolute_deviation == TRUE){
    if(point == TRUE){
      if(density == TRUE){
        result <- unlist(lapply(unique(cp$`_vname_`), function(m){
          sum(abs(weight[[m]] * (cp[cp$`_vname_` == m, "_yhat_"] - unlist(unname(obs["_yhat_"])))))
        }))
      }else{
        result <- unlist(lapply(unique(cp$`_vname_`), function(w){
          sum(abs((cp[cp$`_vname_` == w, "_yhat_"] - unlist(unname(obs["_yhat_"])))))
        }))
      }
    }else{
      if(density == TRUE){
        result <- unlist(lapply(unique(cp$`_vname_`), function(m){
          sum(abs(weight[[m]] *(cp[cp$`_vname_` == m, "_yhat_"] - avg_yhat[[m]])))
        }))
      }else{
        result <- unlist(lapply(unique(cp$`_vname_`), function(w){
          sum(abs((cp[cp$`_vname_` == w, "_yhat_"] - avg_yhat[[w]])))
        }))
      }
    }
  }else{
    if(point == TRUE){
      if(density == TRUE){
        result <- unlist(lapply(unique(cp$`_vname_`), function(m){
          sqrt(sum((weight[[m]] * (cp[cp$`_vname_` == m, "_yhat_"] - unlist(unname(obs["_yhat_"]))))^2)/length(cp[cp$`_vname_` == m, "_yhat_"]))
        }))
      }else{
        result <- unlist(lapply(unique(cp$`_vname_`), function(w){
          sqrt(sum((cp[cp$`_vname_` == w, "_yhat_"] - unlist(unname(obs["_yhat_"])))^2)/length(cp[cp$`_vname_` == w, "_yhat_"]))
        }))
      }
    }else{
      if(density == TRUE){
        result <- unlist(lapply(unique(cp$`_vname_`), function(m){
          sqrt(sum((weight[[m]] * (cp[cp$`_vname_` == m, "_yhat_"] - avg_yhat[[m]]))^2)/length(cp[cp$`_vname_` == m, "_yhat_"]))
        }))
      }else{
        result <- unlist(lapply(unique(cp$`_vname_`), function(w){
          sqrt(sum((cp[cp$`_vname_` == w, "_yhat_"] - avg_yhat[[w]])^2)/(length(cp[cp$`_vname_` == w, "_yhat_"])))
        }))
      }
    }
  }

  cat("Results: \n")
  cat(paste0(unique(cp$`_vname_`), ": ", result, "\n"))
  lvivo = data.frame(variable_name = unique(cp$`_vname_`), measure = result)
  class(lvivo) = c("local_importance", "data.frame")
  lvivo
}

